language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev

script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD --check-bounds=yes --inline=no -e 'import Pkg; Pkg.build("SearchBall"); Pkg.test(; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  # create docu
  # - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
