language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev

script:
 - julia --check-bounds=yes --inline=no -e 'import Pkg; Pkg.build("SearchBall"); Pkg.test(; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SearchBall")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # create docu
  - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
